[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./broadcast" }
]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532 }
base = { key = "${BASESCAN_API_KEY}", chain = 8453 }

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"
